name: bibbler
version: 0.0.0
author: Jonah Spear <jspear@aha-net.org>
description: A simple tile-matching word game.
homepage: https://github.com/joboman/Bibbler
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
